Update filterlisttag.json for additions of Hagezi
collinbarrett/FilterLists pull request #3377
Opened 2023-01-05 17:48 UTC by GiddyGoatGaming

2023-01-05 17:52 UTC, GiddyGoatGaming commented
I really hope i did this right. I was following the instructions by dandelionsprout and collinbarrett but I may have missed something

2023-01-05 18:06 UTC, GiddyGoatGaming commented
just realized hagezi's list are already added smh. il be closing this now. sorry

2023-01-05 18:08 UTC, collinbarrett commented
> just realized hagezi's list are already added smh. il be closing this now. sorry

Ah! Ok, thanks. FWIW, the PR was pretty good. Thanks for contributing.

2023-01-05 18:14 UTC, GiddyGoatGaming commented
> > just realized hagezi's list are already added smh. il be closing this now. sorry
> 
> Ah! Ok, thanks. FWIW, the PR was pretty good. Thanks for contributing.

actually what I could do is add a different formatting of HaGezi's lists, il reopen this and change it to match the rest but for a different format!

2023-01-05 19:24 UTC, GiddyGoatGaming commented
Am i missing anything else? I think i did the repositories I'm required

2023-01-05 21:52 UTC, collinbarrett requested changes

2023-01-05 23:50 UTC, collinbarrett commented
Hmm, the build is complaining about some kind of syntax error in `FilterList.json`. I'm not spotting what it is at the moment.

2023-01-05 23:56 UTC, GiddyGoatGaming commented
> Hmm, the build is complaining about some kind of syntax error in `FilterList.json`. I'm not spotting what it is at the moment.

Il check it out:)

2023-01-06 14:06 UTC, collinbarrett commented
I'll take another look when I get a minute.

In the meantime, would you mind wiring up some new entries in `FilterListMaintainer.json` (and `Maintainer.json` if needed) as well just to keep these new lists clustered together by maintainer? Thanks.

2023-01-06 14:07 UTC, GiddyGoatGaming commented
> I'll take another look when I get a minute.
> 
> In the meantime, would you mind wiring up some new entries in `FilterListMaintainer.json` (and `Maintainer.json` if needed) as well just to keep these new lists clustered together by maintainer? Thanks.

Yep, il do that in a little bit👍

2023-01-06 15:03 UTC, GiddyGoatGaming commented
And done:)

2023-01-07 19:46 UTC, collinbarrett commented on services/Directory/data/FilterListViewUrl.json
> +    "filterListId": 2635
```suggestion
    "filterListId": 2635,
```

2023-01-07 19:52 UTC, collinbarrett approved these changes

2023-01-07 20:02 UTC, merged

2023-01-07 20:03 UTC, GiddyGoatGaming commented
Thank you🙏